context:
  name: fairical
  version: "2.0.2"
  python_min: 3.11

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/fairical-${{ version }}.tar.gz
  sha256: 078a2d310da1b8861e74c07bae68270d113f65af8ddbb6681337fd79dbc34794

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - fairical = fairical.scripts.cli:cli

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - versioningit
    - pip
  run:
    - python >=${{ python_min }}
    - click
    - numpy
    - matplotlib-base
    - scikit-learn
    - fairlearn
    - pydantic >=2
    - pymoo
    - tabulate
    - compact-json

tests:
  - python:
      imports:
        - fairical
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
    script:
      - fairical --help

about:
  homepage: https://gitlab.idiap.ch/medai/software/fairical
  documentation: https://fairical.readthedocs.io/en/latest/
  summary: Fairical is a Python library to assess adjustable demographically fair Machine Learning (ML) systems
  license: GPL-3.0-or-later
  license_file: LICENSES/GPL-3.0-or-later.txt

extra:
  recipe-maintainers:
    - anjos
